config/routes.rb
Rails.application.routes.draw do 
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :products, only: [:index, :create, :new]  do 
    resources :reviews, only: [:index, :new]
  end 
  resources :reviews, only: :create
  get '/products/makeup', to: 'products#makeup'
  get '/products/cleanser', to: 'products#cleanser'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/myreviews', to: 'reviews#myreviews'

  get '/auth/:provider/callback', to: 'sessions#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_many :reviews
    has_many :users, through: :reviews
    validates_presence_of :brand, :title, :category 
    scope :cleanser, -> {where(category: 'Cleanser')}
    scope :makeup, -> {where(category: 'Makeup')}
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :product
    validates_presence_of :description
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :reviews
    has_many :products, through: :reviews
    validates_presence_of :username, :password 
    validates_uniqueness_of :username
    has_secure_password 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        User.find_by(id: session[:user_id])
    end 

    def require_login
        redirect_to login_path unless logged_in?
    end 

    def logged_in?
        !!current_user
    end 

    def log_in(user)
        session[:user_id]=user.id 
    end 

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all 
    end 

    def show
    end 

    def new
        require_login
        @product=Product.new
    end 

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to new_product_review_path(@product)
        else 
            render :new 
        end 
    end 

    def cleanser
        @products= Product.cleanser
        render :index
    end 

    def makeup
        @products= Product.makeup
        render :index
    end 

    def myreviews
       @products= Product.myreviews
       render :index 
    end 


    private

    def product_params
        params.require(:product).permit(:brand, :title, :category, :img)
    end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :get_product, except: :create

def index
end 

def new
    require_login
    @review=Review.new 
end 

def create
    @product= Product.find_by(id: params[:review][:product_id])
    product_nil
    @review= current_user.reviews.build(review_params) 
    if @review.save
        redirect_to product_reviews_path(@review.product)
    else 
         render :new
    end 
end 

def myreviews
    @myreviews=current_user.reviews
end 

private 

def product_nil
    redirect_to products_path if !@product
end 

def get_product
    @product ||= Product.find_by(id: params[:product_id])
end 

def review_params 
    params.require(:review).permit(:category_id, :description, :product_id)
end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end 

def create
    # if a user logged in with omniauth (how we can tell?)
    if request.env["omniauth.auth"] 
        # then find or create in the db by uid 
        @user= User.find_by(github_uid: request.env["omniauth.auth"]["uid"])
        if @user.nil?
            @user=User.create(username: request.env["omniauth.auth"]["info"]["nickname"], github_uid: request.env["omniauth.auth"]["uid"], password: "github")       
        end 
        successful_login
    else 
        # locally authenticate the user - verify  they exist in the db by username
        # and that thir password matches what is in the db
        @user= User.find_by(username: params[:username])
        if !@user
             @error = "Account not found. Please try again." 
            render :new
        # otherwise, re render the login form, displaying a meaningful error
        elsif !@user && @user.authenticate(params[:password])
             @error = "Password Incorrect. Please try again"
             render :new 
        else 
        # if it does, "log them in" with the session hash
        # and redirect them to a meaningful place
        successful_login
    end 
 end 
end

def destroy
    session.clear 
    redirect_to products_path
end 

private 

def successful_login
    log_in(@user)
    redirect_to products_path
end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to products_path 
        else 
            render :new
        end 
    end 


    private 

    def user_params 
        params.require(:user).permit(:username, :password, :password_confirmation)
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end 

    def logged_in?
        !!current_user
    end 
end

app/views/layouts/_navbar.html.erb
<div class="header">
  <div class="title"> Reviews </div>
  <% if current_user %>
    <div class="username">
        <i>Welcome, <%= current_user.username %></i>
    </div>
<% end %>
<div class="nav">
<p><div><a href="/products"> Products </a></div></p> 
<% if logged_in? %>
       <div><a href="/logout"> Log Out</a></div>
<% else %>
        <div><a href="/signup">Sign Up</a></div>
        <div><a href="/login">Log In</a></div> 
   <% end %>
   </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Reviews</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
   <navbar>
      <%= render 'layouts/navbar' %>
   </navbar>
   <main class="wrapper">
      <%= yield %>
      </main>
  </body>
</html>

app/views/products/index.html.erb
<h2> Products </h2> 

<%= link_to "Create New Product", new_product_path %>
<%= link_to "All Products", products_path %>
<%= link_to "Only Cleansers", products_cleanser_path %>
<%= link_to "Only Makeup", products_makeup_path %>


<% @products.each do |product| %>
   <p> <%= product.brand %></p>
   <p> <%= product.title %></p>
   <p> <%= product.category %></p>
   <img src=<%=product.img %>>
   <h3><%= link_to product.title, product_reviews_path(product) %></h3>
   <p><%= product.reviews.count %> reviews</p>
<% end %>

app/views/products/new.html.erb
<h2>Create a New Product</h>

<%= render partial: '/errors', locals: { record: @product } %>

<%= form_for @product do |f| %>
   <p> <%= f.label :brand %>
   <%= f.text_field :brand %> </p>
   <p><%= f.label :title %>
   <%= f.text_field :title %></p>
   <p><%= f.label :category %>
   <%= f.text_field :category %></p>
   <p><%= f.label :image %>
   <%= f.text_field :img %></p>
   <p><%= f.submit "Create Product and Add Review" %> </p>
<% end %>

app/views/reviews/_iteration.html.erb
<% info.each.with_index(1) do |review, index| %>
    <p><h3> <%= review.product.try(:title) %> </h3>
    <h3> <%= index %> </h3>
    <h3> <%= review.description  %></h3>
    by <%= review.user.username %></h3></p>
 <% end %> 


 
    

app/views/reviews/index.html.erb
<h2> All the reviews of <%= @product.title %> </h2>
<%= link_to "Add New Review", new_product_review_path(@product) %> 
<p> <img src=<%=@product.img %>></p>



 <%= render partial: 'reviews/iteration', locals: { info: @product.reviews } %>

app/views/reviews/myreviews.html.erb
<h2> My reviews </h2>


 <%= render partial: 'reviews/iteration', locals: { info: @myreviews } %>

app/views/reviews/new.html.erb
<h2> Add new review on the product <i><%= @product.title %></i> </h2>

<%= render partial: '/errors', locals: { record: @review } %>

<%= form_for @review do |f| %>
   <%=  f.label :description %>
   <%=  f.text_area :description %>
   <%= f.hidden_field :product_id, value: @product.id %>
   <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h2> Create a user account </h2>

<%= render partial: '/errors', locals: { record: @user } %>

<%= form_for @user, url:  signup_path do |f| %>
    <%= f.label :Username %>
    <div><%= f.text_field :username %></div>
    <%= f.label :Password %>
    <div><%= f.password_field :password %></div>
    <%= f.label :confirm_password %>
    <div><%= f.password_field :password_confirmation %>
    <%= f.submit %>
<% end %>